// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateScanEvent(arg1) {
  return window['go']['main']['App']['GenerateScanEvent'](arg1);
}

export function GetDirPathToScan() {
  return window['go']['main']['App']['GetDirPathToScan']();
}

export function GetFilePathToScan() {
  return window['go']['main']['App']['GetFilePathToScan']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}
