// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateScanEvent(arg1:main.UIScanEvent):Promise<void>;

export function GetDirPathToScan():Promise<string>;

export function GetFilePathToScan():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function StartScan(arg1:string):Promise<void>;
